package main
import (
	"fmt"
	"time"
)

func main() {
	fmt.Print("O")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("hh ")
	time.Sleep(500 * time.Millisecond)
	fmt.Print("A")
	time.Sleep(300 * time.Millisecond)
	fmt.Print("s")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("m")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(500 * time.Millisecond)
	fmt.Print("r")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(600 * time.Millisecond)

	fmt.Println()

	fmt.Print("B")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("e")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("r")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("d")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("e")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("b")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("r ")
	time.Sleep(220 * time.Millisecond)
	fmt.Print("r")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("s")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("n")
	time.Sleep(170 * time.Millisecond)
	fmt.Print("y")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(800 * time.Millisecond)

	fmt.Println()

	fmt.Print("K")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("u ")
	time.Sleep(300 * time.Millisecond)
	fmt.Print("d")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("i")
	time.Sleep(300 * time.Millisecond)
	fmt.Print("-d")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("e")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("k")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("t")
	time.Sleep(300 * time.Millisecond)
	fmt.Print("m")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("u")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("u")
	time.Sleep(800 * time.Millisecond)

	fmt.Println("\n")

	fmt.Print("O")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("hh ")
	time.Sleep(500 * time.Millisecond)
	fmt.Print("A")
	time.Sleep(300 * time.Millisecond)
	fmt.Print("s")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("m")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(300 * time.Millisecond)
	fmt.Print("r")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(600 * time.Millisecond)

	fmt.Println()
	
	fmt.Print("D")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("e")
	time.Sleep(220 * time.Millisecond)
	fmt.Print("n")
	time.Sleep(20 * time.Millisecond)
	fmt.Print("g")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("r ")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("b")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("i")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("s")
	time.Sleep(20 * time.Millisecond)
	fmt.Print("i")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("k")
	time.Sleep(70 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(70 * time.Millisecond)
	fmt.Print("n ")
	time.Sleep(230 * time.Millisecond)
	fmt.Print("c")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("i")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("n")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("t")
	time.Sleep(80 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(320 * time.Millisecond)

	fmt.Println()
	
	fmt.Print("L")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("i")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("r")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("i")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("h ")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("m")
	time.Sleep(70 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("t")
	time.Sleep(70 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(250 * time.Millisecond)
	fmt.Print("m")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("u")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("u")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("~")
	time.Sleep(1500 * time.Millisecond)

	fmt.Println("\n")

	fmt.Print("O")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("hh ")
	time.Sleep(500 * time.Millisecond)
	fmt.Print("A")
	time.Sleep(300 * time.Millisecond)
	fmt.Print("s")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("m")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(300 * time.Millisecond)
	fmt.Print("r")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(600 * time.Millisecond)

	fmt.Println()

	fmt.Print("B")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("l")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("s ")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("s")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("i")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("n")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("y")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("l ")
	time.Sleep(120 * time.Millisecond)
	fmt.Print("c")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("i")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("n")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("t")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("k")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("u")
	time.Sleep(1600 * time.Millisecond)

	fmt.Println()
	
	fmt.Print("S")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("e")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("k")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("l")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("i ")
	time.Sleep(120 * time.Millisecond)
	fmt.Print("s")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("j")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("~")
	time.Sleep(1200 * time.Millisecond)

	fmt.Println("\n")

	fmt.Print("O")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("hh ")
	time.Sleep(500 * time.Millisecond)
	fmt.Print("A")
	time.Sleep(300 * time.Millisecond)
	fmt.Print("s")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("m")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(300 * time.Millisecond)
	fmt.Print("r")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(600 * time.Millisecond)

	fmt.Println()

	
	fmt.Print("T")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("i")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("d")
	time.Sleep(70 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("k ")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(70 * time.Millisecond)
	fmt.Print("d")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(160 * time.Millisecond)
	fmt.Print("k")
	time.Sleep(70 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(70 * time.Millisecond)
	fmt.Print("h ")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("r")
	time.Sleep(70 * time.Millisecond)
	fmt.Print("u")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(30 * time.Millisecond)
	fmt.Print("n")
	time.Sleep(30 * time.Millisecond)
	fmt.Print("g ")
	time.Sleep(300 * time.Millisecond)
	fmt.Print("d")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("l")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(50 * time.Millisecond)
	fmt.Print("m ")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("h")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("a")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("t")
	time.Sleep(100 * time.Millisecond)
	fmt.Print("i")
	time.Sleep(150 * time.Millisecond)
	fmt.Print("m")
	time.Sleep(250 * time.Millisecond)
	fmt.Print("u")
	time.Sleep(700 * time.Millisecond)
	fmt.Print("~")
	time.Sleep(1500 * time.Millisecond)

	fmt.Println()

	fmt.Print("T")
	time.Sleep(90 * time.Millisecond)
	fmt.Print("e")
	time.Sleep(90 * time.Millisecond)
	fmt.Print("r")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("s")
	time.Sleep(90 * time.Millisecond)
	fmt.Print("i")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("s")
	time.Sleep(90 * time.Millisecond)
	fmt.Print("a ")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("u")
	time.Sleep(90 * time.Millisecond)
	fmt.Print("n")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("t")
	time.Sleep(90 * time.Millisecond)
	fmt.Print("u")
	time.Sleep(90 * time.Millisecond)
	fmt.Print("k")
	time.Sleep(200 * time.Millisecond)
	fmt.Print("k")
	time.Sleep(90 * time.Millisecond)
	fmt.Print("u")
	time.Sleep(800 * time.Millisecond)
	fmt.Print("?")
	time.Sleep(1500 * time.Millisecond)	
}